## critical fit NG $\beta=5.85$  {#critical_fit_NG_beta585}

```{r , include=FALSE}
 knitr::opts_chunk$set(echo = FALSE, warning = FALSE, result='asis')
 
 library(ggplot2)
 library(plotly)
 library(tidyverse)
 library(htmlwidgets)
 library(pander)
 #library(latex2exp)
 library(knitr)
 library(dplyr) #data frame manipulation
 require(scales) # to access break formatting functions
 #library(shiny)
 #library(shinyWidgets)
 library(ggrepel)
 library(Rose)
 library(widgetframe)
 require("processx")
 library(webshot)
 library(htmltools)
```

we fit $m_{PCAC}$ and $M_{PS}^2$ with the formule

$$
\begin{cases}
m_{PCAC}=P[0] + P[2] (\eta- \eta_{cr})  + P[4] \mu\\
M_{PS}^2=P[1] + P[3] (\eta- \eta_{cr})  + P[5] \mu +P[6] (\eta- \eta_{cr})^2\,.
\end{cases}
$$

The coefficient $P[0]$ and $P[1]$ represent the value of $m_{PCAC}$ and $M_{PS}^2$ at $\eta_{cr}$ and $\mu=0$. We are assuming that we are simulating at $m_{cr}$

```{r , child="../fit_all_out/fit_NG_mpcac_MPS_b585_fit_P.tex", eval=TRUE}
```



```{r, echo=FALSE, results='asis'}
file=sprintf("../fit_all_out/fit_NG_mpcac_MPS_b585_fit_data.txt")
dfn<- read.table(file, header=FALSE, fill=TRUE)
#names(df) <- c("$L$","$k/m$","err", "$T$","$q2$")
#df<- df[c("$T$","$L$","$k/m$","err" ,"$q2$")] 
#kable(df[,-5],digit=20)
n0<-which(dfn[,1]==0)
df0<-dfn[n0,]
n1<-which(dfn[,1]==1)
df1<-dfn[n1,]
gg<- ggplot()
gg<-gg+  geom_point(data=df0, mapping=aes(x=df0[,7] , y=df0[,2],
                          color=as.factor(df1[,10]), fill=as.factor(df1[,10]),
                          shape=as.factor(df1[,9])  ) ,width=0.001)+labs(color = "momentum")
gg<-gg + geom_errorbar(data=df0, mapping=aes(x=df0[,7] , ymin=df0[,2]-df0[,3],
                          ymax=df0[,2]+df0[,3],
                          color=as.factor(df1[,10]), fill=as.factor(df1[,10]),
                          shape=as.factor(df1[,9]) ) ,width=0.001)


datalist = list()
n<-0
for (en in c(1:length(df0[,1])) ){
   
  file=sprintf("../fit_all_out/fit_NG_mpcac_MPS_b585_fit_out_n%d_en%d_eta.txt",n,en-1)
  datalist[[en]]<- read.table(file, header=FALSE, fill=TRUE,   
                  col.names=c(paste0("x",n),paste0("fit",n),paste0("fiterr",n)))
 
  gg<-gg + geom_ribbon(data=datalist[[en]], 
                       mapping=aes_string(x=datalist[[en]][,1] ,
                                          ymin=datalist[[en]][,2]-datalist[[en]][,3], 
                                          ymax=datalist[[en]][,2]+datalist[[en]][,3],
                                          color=as.factor(df1[en,10]), fill=as.factor(df1[en,10]),
                                          shape=as.factor(df1[en,9])),
                        alpha=0.5,  )
 
}

gg<- gg+theme_bw() #+ ggplot2::coord_cartesian(xlim=c(0,0.05), ylim=c(-3,0 ))

fig_pdf<- myplotly(gg,"", "$\\eta$", "$m_{pcac}$",  output="AUTO",to_print = FALSE)%>% add_annotations( text="$(\\color{red}{m}_{\\color{cyan}0},\\mu_3)$", xref="paper", yref="paper",
                  x=1.10, xanchor="left",
                  y=0.75, yanchor="bottom",    # Same y as legend below
                  legendtitle=TRUE, showarrow=FALSE ) %>%
  layout( legend=list(y=0.7, yanchor="top",title=F ) )

fig_pdf

```






```{r, echo=FALSE, results='asis'}

gg<- ggplot()
gg<-gg+  geom_point(data=df0, mapping=aes(x=df1[,7] , y=df1[,2],
                          color=as.factor(df1[,10]), fill=as.factor(df1[,10]),
                          shape=as.factor(df1[,9]) ),  width=0.001)+labs(color = "momentum")
gg<-gg + geom_errorbar(data=df0, mapping=aes(x=df1[,7] , ymin=df1[,2]-df1[,3],
                          ymax=df1[,2]+df1[,3],
                          color=as.factor(df1[,10]), fill=as.factor(df1[,10]),
                          shape=as.factor(df1[,9])) ,width=0.001)

datalist = list()
n<-1
for (en in c(1:length(df1[,1])) ){
   
  file=sprintf("../fit_all_out/fit_NG_mpcac_MPS_b585_fit_out_n%d_en%d_eta.txt",n,en-1)
  datalist[[en]]<- read.table(file, header=FALSE, fill=TRUE,   
                  col.names=c(paste0("x",n),paste0("fit",n),paste0("fiterr",n)))
 
  gg<-gg + geom_ribbon(data=datalist[[en]], mapping=aes_string(x=datalist[[en]][,1] ,    ymin=datalist[[en]][,2]-datalist[[en]][,3], ymax=datalist[[en]][,2]+datalist[[en]][,3], 
color=as.factor(df1[en,10]), fill=as.factor(df1[en,10]),
                          shape=as.factor(df1[en,9])                                                                ),alpha=0.5,  )
 
}

gg<- gg+theme_bw() #+ ggplot2::coord_cartesian(xlim=c(0,0.05), ylim=c(-3,0 ))
gg<- gg+labs(color = "", shape= "")
fig_pdf<- myplotly(gg,"", "$\\eta$", "$M_{PS}^2$",  output="AUTO",to_print = FALSE)%>% add_annotations( text="$(\\color{red}{m}_{\\color{cyan}0},\\mu_3)$", xref="paper", yref="paper",
                  x=1.10, xanchor="left",
                  y=0.75, yanchor="bottom",    # Same y as legend below
                  legendtitle=TRUE, showarrow=FALSE ) %>%
  layout( legend=list(y=0.7, yanchor="top",title=F ) )

fig_pdf

```
