
# Scaling $\phi$

here we perform a test running a simulation with 
$$
\phi_c =\phi/\sqrt{2 \kappa} ,\quad \eta_c=\eta \sqrt{2 \kappa} , \quad \rho_c=\rho\sqrt{2 \kappa}
$$
the value chosen are:
  
  - $\eta=-1.0983 \to \eta_c=-0.56$  
  
  - $\rho=1.96   \to  \rho_c=1$
  
  - $\kappa=0.130$

```{r , include=FALSE}
 knitr::opts_chunk$set(echo = FALSE, warning = FALSE, result='asis')
 
 library(ggplot2)
 library(plotly)
 library(tidyverse)
 library(htmlwidgets)
 library(pander)
 #library(latex2exp)
 library(knitr)
 library(dplyr) #data frame manipulation
 require(scales) # to access break formatting functions
 #library(shiny)
 #library(shinyWidgets)
 library(ggrepel)
 library(Rose)
 library(widgetframe)
 require("processx")
 library(webshot)
 library(htmltools)


df <- data.frame(x = 1:5, y = 1:5)    
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knitr handle the rendering naturally
```




```{r,echo=FALSE,results='asis', dev='tikz',  fig.width = 9, include=FALSE}
gdf<-data.frame("T"=c(0),"L"=c(0),"rho"=c(0),"eta"=c(0),"csw"=c(0),"mu03"=c(0),"m0"=c(0),"m_ps"=c(0),"m_Ds3"=c(0),"m_S0"=c(0),"r_awi"=c(0),"m_pcac"=c(0))
gdferr<-data.frame("T"=c(0),"L"=c(0),"rho"=c(0),"eta"=c(0),"csw"=c(0),"mu03"=c(0),"m0"=c(0),"m_ps"=c(0),"m_ps_err"=c(0),"m_Ds3"=c(0),"m_Ds3_err"=c(0),"m_S0"=c(0),"m_S0_err"=c(0),"r_awi"=c(0),"r_awi_err"=c(0),"m_pcac"=c(0),"m_pcac_err"=c(0))

gdf<-gdf[-1,]
gdferr<-gdferr[-1,]
#"b5.85/L20T40/eta_m1.1375_M02_-0.024604_mu03_0.0120_csw_1.0_rho1.96",

dirs<-c("b5.85/L20T40/scaling_phi_test/eta_m1.0983_M02_-0.010396_mu03_0.0224_csw_1.0_rho1.96",
        "b5.85/L20T40/scaling_phi_test/eta_m1.0983_M02_-0.010396_mu03_0.0224_csw_1.0_rho1.96_normalization"
        )
count=1
for (dir in dirs){
  cat('\n\n## ',dir,'\n\n')

file=sprintf("../%s/data/phit",dir)
   all_file <- read.table(file,header=FALSE,fill = TRUE ,
                         blank.lines.skip=FALSE,skip=0, comment.char = "")
head<-data.frame(c(0))
head<-head[,-1]
head$T<-all_file[1,2]
head$L<-all_file[2,2]
head$rho<-all_file[3,2]
head$eta<-all_file[4,2]
head$csw<-all_file[5,2]
head$mu03<-all_file[6,2]
head$m0<-all_file[7,2]
print(kable(head))
l<-head[1,]
lerr<-head[1,]
file=sprintf("../%s/out/T%d_L%d_output",dir,head$T,head$L)
# cat("\n ##", file,'\n\n')
# 
mt<-read_df(file)
all_obs<- get_all_corr(mt)
 
 
 
for  (n in all_obs$n){
  gg<-ggplot()
  label<-all_obs$corr[n]
  label<-paste0("$",label,"$")
  d<- get_block_n(mt,n)
  fit<- get_fit_n(mt,n)
  fit_range<- get_plateaux_range(mt,n)
  # mydf<-reshape_df_analysis_to_ggplot(d)
  # gg <- gg + ggplot2::geom_point(data=mydf,mapping=aes(x=x, y=y),inherit.aes = FALSE)
  # 
  # gg <- gg +ggplot2::geom_errorbar(data=mydf, mapping=aes(x=x, ymin=y-err, ymax=y+err),
  #                                  width = 0.3,inherit.aes = FALSE)
  # 
  # 
  # gg <- gg +ggplot2::geom_ribbon( data=mydf,
  #               mapping=aes(x=xfit, ymin=fit-errfit,ymax=fit+errfit ),color=NA
  #                                 ,alpha=0.2      ,inherit.aes = FALSE, show.legend = FALSE)
  # fit_range<-fit_range
  # 
  # gg <- gg+ ggplot2::geom_line(data=mydf, aes(x=fit_range[1],y=y),alpha=0.3, linetype="dashed",)
  # gg <- gg+ ggplot2::geom_line( data=mydf ,aes(x=fit_range[2],y=y),alpha=0.3, linetype="dashed")
  # gg <- gg+ggplot2::theme_bw()
  gg<- many_fit_ggplot(d,fit,fit_range,length(d),"no",gg,label  )
 # 
  
cat('\n\n ',label,"=", mean_print(fit[1,1],fit[1,2]),'\n\n')
 l<-append(l, mean_print(fit[1,1],fit[1,2]))
 lerr<-append(lerr, list(fit[1,1],fit[1,2]))

#  # plot(gg)
# fig<-ggplotly(gg,dynamicTicks = TRUE)%>%
#        layout(   yaxis = list( title = TeX("c(t)"),showexponent = "all", exponentformat = "e")  ,xaxis = list(title = TeX("t") ) )
# 
# cat("\n\n")
# print(htmltools::tagList(fig))
# cat("\n\n")

title<- paste0(label)
myplotly(gg, label,'$x_0/a$',label )



  

}
  gdf[count,]<-l
  gdferr[count,]<-lerr
 count=count+1
}


# kable(gdf)

```

## compare plots

```{r, echo=FALSE,results='asis', dev='tikz',  fig.width = 9}

T<- 40
L<-20
dir<-"b5.85/L20T40/scaling_phi_test/eta_m1.0983_M02_-0.010396_mu03_0.0224_csw_1.0_rho1.96"   
file=sprintf("../%s/out/T%d_L%d_output",dir,T,L)
dir1<-"b5.85/L20T40/scaling_phi_test/eta_m1.0983_M02_-0.010396_mu03_0.0224_csw_1.0_rho1.96_normalization"
file1=sprintf("../%s/out/T%d_L%d_output",dir1,T,L)

mt<-read_df(file)
all_obs<- get_all_corr(mt)

mt1<-read_df(file1)
all_obs1<- get_all_corr(mt1)

all_obs<- get_all_corr(mt)



 
for  (n in all_obs$n){
  gg<-ggplot()
  label<-all_obs$corr[n]
  d<- get_block_n(mt,n)
  fit<- get_fit_n(mt,n)
  fit_range<- get_plateaux_range(mt,n)
  gg<- many_fit_ggplot(d,fit,fit_range,length(d),"no",gg,label  )
  
  label1<-paste(label,"code")
  d1<- get_block_n(mt1,n)
  d1[,1]<-d1[,1]+0.1
  fit1<- get_fit_n(mt1,n)
  fit_range1<- get_plateaux_range(mt1,n)
  gg<- many_fit_ggplot(d1,fit1,fit_range1,length(d1),"no",gg,label1  )
  
cat('\n\n ',label,"=", mean_print(fit[1,1],fit[1,2]),'\n\n')


title<- paste0(label)
myplotly(gg, label,'$x_0/a$',label )



  

}



```


## Summary table scaling

```{r,echo=FALSE,results='asis',}

DT::datatable(gdf[,c(-1,-2,-5, -9)],filter = 'bottom',  rownames= FALSE)

#DT::datatable(gdf[,c(1:7,8,9)],filter = 'bottom')
#DT::datatable(gdf[,c(1:7,10,11)],filter = 'bottom')
#DT::datatable(gdf[,c(1:7,12)],filter = 'bottom')
```

## Summary Plots scaling

```{r,results='asis', dev='tikz',fig.width=8.2}
gg<- ggplot(gdferr)+geom_point(aes(x=eta, y=m_ps,color=as.factor(m0),shape=as.factor(mu03) ),size=3 )
gg<- gg +geom_errorbar(aes(x=eta, ymin=m_ps-m_ps_err, ymax=m_ps+m_ps_err, color=as.factor(m0),shape=as.factor(mu03)  ),width=0.01)
gg<- gg+ theme_bw()+theme( legend.title = element_blank() )
ggplotly(gg,dynamicTicks = TRUE)%>%
       layout(   yaxis = list( title = TeX("M_{PS}"),showexponent = "all", exponentformat = "e")  ,xaxis = list(title = TeX("\\eta") ) ) %>% add_annotations( text="$(\\color{red}{m_{\\color{blue}0}},\\mu_3)$", xref="paper", yref="paper",
                  x=1.10, xanchor="left",
                  y=0.8, yanchor="bottom",    # Same y as legend below
                  legendtitle=TRUE, showarrow=FALSE ) %>%
  layout( legend=list(y=0.8, yanchor="top" ) )
```

```{r,results='asis', dev='tikz',fig.width=8.2}
gg<- ggplot(gdferr)+geom_point(aes(x=eta, y=r_awi,color=as.factor(m0),shape=as.factor(mu03) ),size=3 )
gg<- gg +geom_errorbar(aes(x=eta, ymin=r_awi-r_awi_err, ymax=r_awi+r_awi_err, color=as.factor(m0),shape=as.factor(mu03)  ),width=0.01)
gg<- gg+ theme_bw()+theme( legend.title = element_blank() )

ggplotly(gg,dynamicTicks = TRUE)%>%
       layout(   yaxis = list( title = TeX("r_{AWI}"),showexponent = "all", exponentformat = "e")  ,xaxis = list(title = TeX("\\eta") ) ) %>% add_annotations( text="$(\\color{red}{m_{\\color{blue}0}},\\mu_3)$", xref="paper", yref="paper",
                  x=1.10, xanchor="left",
                  y=0.8, yanchor="bottom",    # Same y as legend below
                  legendtitle=TRUE, showarrow=FALSE ) %>%
  layout( legend=list(y=0.8, yanchor="top" ) )
```

```{r,results='asis', dev='tikz', fig.width = 8.2 }
gg<- ggplot(gdferr)+geom_point(aes(x=eta, y=m_pcac,color=as.factor(m0),shape=as.factor(mu03) ),size=3 )
gg<- gg +geom_errorbar(aes(x=eta, ymin=m_pcac-m_pcac_err, ymax=m_pcac+m_pcac_err, color=as.factor(m0),shape=as.factor(mu03)  ),width=0.01)
gg<- gg+ theme_bw()+theme( legend.title = element_blank() )

fig<-ggplotly(gg,dynamicTicks = TRUE) %>% add_annotations( text="$(\\color{red}{m}_{\\color{blue}0},\\mu_3)$", xref="paper", yref="paper",
                  x=1.10, xanchor="left",
                  y=0.8, yanchor="bottom",    # Same y as legend below
                  legendtitle=TRUE, showarrow=FALSE ) %>%
  layout( legend=list(y=0.8, yanchor="top" ) )%>%
       layout(   yaxis = list( title = "$m_{pcac}$",showexponent = "all", exponentformat = "e")  ,xaxis = list(title = TeX("\\eta") ) ) 

fig #print(htmltools::tagList(fig))

```